// This is a custom component - https://github.com/getAlby/go/pull/279
// Do NOT edit this file while upgrading react native primitive components

import * as React from "react";
import { TextProps } from "react-native";
import Animated from "react-native-reanimated";
import { cn } from "~/lib/utils";

function Skeleton({ className, ...props }: Omit<TextProps, "style">) {
  return (
    <Animated.Text
      style={{
        animationName: {
          from: { opacity: 0.4 },
          to: { opacity: 1 },
        },
        animationDuration: "1s",
        animationIterationCount: "infinite",
        animationTimingFunction: "ease-in-out",
        animationDirection: "alternate",
      }}
      className={cn("rounded-md bg-muted", className)}
      {...props}
    />
  );
}

export { Skeleton };
